// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiPlPWVVa-Z-Agnw3DsehipvDRo4T9uA',
    appId: '1:351702110827:web:8a89b769eb1746b6ffd72e',
    messagingSenderId: '351702110827',
    projectId: 'authtutorial-64502',
    authDomain: 'authtutorial-64502.firebaseapp.com',
    storageBucket: 'authtutorial-64502.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUv-bquQHT3nhO3V5l9aSC_ljJ49lz2Sw',
    appId: '1:351702110827:android:7a7ba738c09783e8ffd72e',
    messagingSenderId: '351702110827',
    projectId: 'authtutorial-64502',
    storageBucket: 'authtutorial-64502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUChESHuLAW5It1gQbf2d-7nyZKyRJ9DA',
    appId: '1:351702110827:ios:651458318494e1c6ffd72e',
    messagingSenderId: '351702110827',
    projectId: 'authtutorial-64502',
    storageBucket: 'authtutorial-64502.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUChESHuLAW5It1gQbf2d-7nyZKyRJ9DA',
    appId: '1:351702110827:ios:651458318494e1c6ffd72e',
    messagingSenderId: '351702110827',
    projectId: 'authtutorial-64502',
    storageBucket: 'authtutorial-64502.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJiPlPWVVa-Z-Agnw3DsehipvDRo4T9uA',
    appId: '1:351702110827:web:cdaf5765245237ecffd72e',
    messagingSenderId: '351702110827',
    projectId: 'authtutorial-64502',
    authDomain: 'authtutorial-64502.firebaseapp.com',
    storageBucket: 'authtutorial-64502.firebasestorage.app',
  );
}
